spring:
  datasource:
    url: *********
    username: *********
    password: *********

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB



  mail:
    host: smtp.gmail.com
    port: ***
    username: "******"
    password: "******"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

# app password: qtlh gjkc ztda xxls

#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password:
#    key-store-type: PKCS12
#    key-alias:

logging:
  level:
    root: DEBUG
    com.traderbird: DEBUG

jwt:
  secret: *******************************
  expiration: 86400000

server:
  tomcat:
    connection-timeout: 60000
